// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package pgImpl

import (
	"context"
)

type Querier interface {
	ExistsTopic(ctx context.Context, name string) (bool, error)
	ExistsUser(ctx context.Context, email string) (bool, error)
	FindAllTopicsByUserID(ctx context.Context, userID int32) ([]Topic, error)
	FindAllUsersByTopicName(ctx context.Context, name string) ([]User, error)
	FindNotificationByID(ctx context.Context, id int64) (Notification, error)
	FindTopicByName(ctx context.Context, name string) (Topic, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserTopicsByTopicID(ctx context.Context, userID int32) (UserTopic, error)
	FindUserTopicsByUserID(ctx context.Context, topicID int32) (UserTopic, error)
	SaveNotification(ctx context.Context, arg SaveNotificationParams) (Notification, error)
	SaveTopic(ctx context.Context, name string) (Topic, error)
	SaveUser(ctx context.Context, email string) (User, error)
	SaveUserTopics(ctx context.Context, arg SaveUserTopicsParams) (UserTopic, error)
}

var _ Querier = (*Queries)(nil)
